name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '7.0'
      - run: npm install
      - run: make check
